// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5VBYzk155tufczIaUopP_sYqLFOpAQA',
    appId: '1:1021003153400:web:db0bc14e8c7d1dbccf600d',
    messagingSenderId: '1021003153400',
    projectId: 'flowing-perigee-375408',
    authDomain: 'flowing-perigee-375408.firebaseapp.com',
    storageBucket: 'flowing-perigee-375408.firebasestorage.app',
    measurementId: 'G-L522S6JHNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFanRL8zmbnwZ8tsxtnFym-sLfX4_BrCM',
    appId: '1:1021003153400:android:462673c9b834d21ecf600d',
    messagingSenderId: '1021003153400',
    projectId: 'flowing-perigee-375408',
    storageBucket: 'flowing-perigee-375408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5jPlPMA4Fd-W6Y8Siczrn02SpxH_2Qs',
    appId: '1:1021003153400:ios:ad4d0939e3a6c36fcf600d',
    messagingSenderId: '1021003153400',
    projectId: 'flowing-perigee-375408',
    storageBucket: 'flowing-perigee-375408.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5jPlPMA4Fd-W6Y8Siczrn02SpxH_2Qs',
    appId: '1:1021003153400:ios:ad4d0939e3a6c36fcf600d',
    messagingSenderId: '1021003153400',
    projectId: 'flowing-perigee-375408',
    storageBucket: 'flowing-perigee-375408.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5VBYzk155tufczIaUopP_sYqLFOpAQA',
    appId: '1:1021003153400:web:540b3bf9d168a171cf600d',
    messagingSenderId: '1021003153400',
    projectId: 'flowing-perigee-375408',
    authDomain: 'flowing-perigee-375408.firebaseapp.com',
    storageBucket: 'flowing-perigee-375408.firebasestorage.app',
    measurementId: 'G-997GS0CTRZ',
  );
}
